use std::ffi::OsStr;
use std::fs;
use std::{error::Error, path::PathBuf};
use anyhow::Result;
use std::fs::File;
// use shakmaty::{
//     fen::Fen, san::SanPlus, CastlingMode, Chess, Color, EnPassantMode, Outcome, Position,
// };

// use shakmaty_syzygy::{Material, MaybeRounded, WdlTable};

fn main() -> Result<()>{
    let paths = fs::read_dir("./partial_dl")?;
    let mut o = File::create("material_encoding.rs")?;
    write!(o, "// GENERATED BY ")

    for path_opt in paths {
        if let Ok(path) = path_opt {
            let path_ = path.path();
            let file_name = path_.file_name().unwrap().to_str().unwrap();
            let (material_str, _) = file_name.split_once(".").unwrap();
            // println!("{material_str:?}");
        }
    }

    Ok(())
}